### ISSUE TITLE
Update basic tutorial

### ISSUE THREAD

**Issue by asmie** [eigerco/pallet-move#62]
Deliverable 0b.
We will provide both inline documentation of the code and a basic tutorial that explains how a user can (for example) spin up one of our Substrate nodes and send test transactions, which will show how the new functionality works. 

This task covers updating basic tutorial made in Milestone 1.

**Comment by Rqnsom** [comment]
https://github.com/eigerco/pallet-move/pull/135
https://github.com/eigerco/pallet-move/pull/135
