### ISSUE TITLE
Create static MoveVM  instance within the runtime

### ISSUE THREAD

**Issue by Rqnsom** [eigerco/pallet-move#80]
All extrinsics and RPC calls should use the same MoveVM instance

**Comment by Rqnsom** [comment]
@asmie 
Lowering priority for now since we can use an alternative approach for now:
Create a new MoveVM before accessing the storage since creating the VM isn't expensive. But we are gonna check that more in the future.

**Comment by 35359595** [comment]
have you considered use of offchain worker for this?

**Comment by Rqnsom** [comment]
Not until now
