### ISSUE TITLE
Init MoveVM function API (for loading stdlib move packing)

### ISSUE THREAD

**Issue by Rqnsom** [eigerco/pallet-move#83]
In order to use full stdlib, we will need to initialize MoveVM before the user starts using the stdlib package in their Move contracts.

- [X] 1. Fetch stdlib bundle
- [ ] 2. Implement the init function which publishes the stdlib bundle

**Comment by 35359595** [comment]
this is already implemented in #100

**Comment by Rqnsom** [comment]
https://github.com/eigerco/pallet-move/pull/111
